clear *;
pkg load signal;
subplot_count = 2;
[loopfilter, dsr] = audioread("LoopFilter.wav", "native");
[datafilter, dsr] = audioread("DataFilter.wav", "native");
[thirdmixer, dsr] = audioread("ThirdMixer.wav", "native");
#[audiodither, dsr] = audioread("AudioDither.wav", "native");
subplot(subplot_count,1,1);
plot(loopfilter);
hold on;
plot(datafilter);
hold off;
subplot(subplot_count,1,2);
plot(thirdmixer);
#hold off;
#subplot(subplot_count, 1,3);
#plot(audiodither);
